gui:
  nerdFontsVersion: "3"
  showFileTree: true
  theme:
    activeBorderColor:    ["#58a6ff", bold]
    inactiveBorderColor:  ["#30363d"]
    selectedLineBgColor:  ["#161b22"]
    unstagedChangesColor: ["#f85149"]
